on:
  push:
    branches:
      - "*"
    paths:
      - "inf/python-package-index/**/*"
      - "inf/modules/**/*"
      - ".github/workflows/ppi-terraform-deploy-staging.yaml"
    tags:
      - "python-package-index@v*-staging"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-terraform-configurations-to-python-package-index-stack-staging:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false
      - name: Set up aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo apt install unzip
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
        shell: bash
      - name: Add profile credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile identity
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile identity
        shell: bash
      - name: Add config for profiles
        run: |
          aws configure set region us-east-2 --profile identity
          aws configure set output json --profile identity
          aws configure set region us-east-2 --profile terraform-state
          aws configure set role_arn "arn:aws:iam::592830654455:role/terraform-deployers" --profile terraform-state
          aws configure set source_profile identity --profile terraform-state
          aws configure set region us-east-2 --profile robotics_robot_stack_dev-admin
          aws configure set role_arn arn:aws:iam::699250785121:role/administrator --profile robotics_robot_stack_dev-admin
          aws configure set source_profile identity --profile robotics_robot_stack_dev-admin
          aws configure set region us-east-2 --profile robotics_robot_stack_prod-admin
          aws configure set role_arn arn:aws:iam::879285218407:role/administrator --profile robotics_robot_stack_prod-admin
          aws configure set source_profile identity --profile robotics_robot_stack_prod-admin
        shell: bash
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: inf/python-package-index
        shell: bash
      - name: Terraform Workspace
        id: workspace-setup
        run: terraform workspace select staging
        working-directory: inf/python-package-index
        shell: bash
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        working-directory: inf/python-package-index
        shell: bash
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: inf/python-package-index
        shell: bash
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -var-file=python-package-index.tfvars -no-color -out tf_plan_staging
        working-directory: inf/python-package-index
        shell: bash
      - name: Terraform Show
        id: show
        run: |
          terraform show -no-color tf_plan_staging 2>&1 | tee /tmp/tf_plan_staging.txt
        working-directory: inf/python-package-index
        shell: bash
      - name: Upload Plan
        id: upload-plan
        uses: "actions/upload-artifact@v3"
        with:
          name: "tf_plan_staging.txt"
          path: "/tmp/tf_plan_staging.txt"
      - name: Terraform Apply
        if: startsWith(github.ref, 'refs/tags/python-package-index@') && endsWith(github.ref, '-staging')
        run: |
          terraform apply -input=false tf_plan_staging
        working-directory: inf/python-package-index
        shell: bash
        # the staging environment exists on the same AWS OU as prod.
        # Some resources like OIDC providers are unique-per-account on
        # AWS, and thus this step will fail to apply the OIDC provider
        # (but still work). It is therefore acceptable if this step fails.
        continue-on-error: true
